### ISSUE TITLE
Erreur dans le lien - cela devrait être confirmation.js, pas cart

### ISSUE THREAD

**Issue by bmrejen** [OpenClassrooms-Student-Center/P5-Dev-Web-Kanap#6]
https://github.com/OpenClassrooms-Student-Center/P5-Dev-Web-Kanap/blob/7735212434c3b385f12c68350d5af9c4fd826d81/front/html/confirmation.html#L78

**Comment by lucbourrat** [comment]
that's right, it has since been fixed
